server:
  port: 8000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_SET_URI}
app:
  role:
    reports: ${APP_ROLE_REPORTS}
  oids:
    auth-server-urls: ${APP_OIDS_AUTH_SERVER_URLS}
  http:
    cors:
      headers: ${APP_HTTP_CORS_HEADERS}
      methods: ${APP_HTTP_CORS_METHODS}