server:
  port: 8000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_SET_URI:http://localhost:8080}
app:
  role:
    reports: ${APP_ROLE_REPORTS:user}
  http:
    cors:
      headers: ${APP_HTTP_CORS_HEADERS:authorization}
      methods: ${APP_HTTP_CORS_METHODS:GET}
      origins: ${APP_HTTP_CORS_ORIGINS:*}